apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: mardan-smart-city
type: Opaque
stringData:
  DATABASE_URL: "postgres://admin:securepassword@postgres:5432/mardan_db?sslmode=disable"
  JWT_SECRET: "k3s_super_secret_key"
