apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: mardan-smart-city
type: Opaque
stringData:
  POSTGRES_USER: "admin"
  POSTGRES_PASSWORD: "securepassword"
  POSTGRES_DB: "mardan_db"
